;METADATA=(Diff=true, UseCommands=true)
[/Script/LivestreamingToolkit.OWLSettings]
bAutoLaunchNDIInstaller=False
bDisableHardwareEncoding=False
bSuppressLoginPopup=False
bUseApplicationLicense=False
bEnableOWLDemoLicences=False
bDemoLicencePopupDismissed=True
OWLOfflineAppData=
OWLCameraRenderOutputPath=../../../../../../Unreal/Through_the_Veil/Saved/OWLCameraOutput

